version: "3.8"

services:
  localstack:
    container_name: localstack_corretora
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=lambda,sqs,dynamodb,sns,stepfunctions,events,iam,sts,s3,cloudwatch
      - DEBUG=1
      - LS_LOG=trace
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_UI=1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_STAY_OPEN_MODE=1
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=bridge
      - LAMBDA_STARTUP_TIMEOUT=120
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
